version: '3.7'

services:
    apache-php:
        image: php:7.3-apache
        links:
            - 'mariadb:db'
        ports:
            - 83:80
        volumes:
            - "./DocumentRoot:/var/www/html"
        command: "/bin/sh -c 'docker-php-ext-install mysqli && exec apache2-foreground'"


    mariadb:
        image: mariadb:10.5.2
        volumes: 
            - "./database:/var/lib/mysql"
        environment:
            TZ: "Europe/Madrid"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: 'rootpsw'
            MYSQL_USER: 'r00t'
            MYSQL_PASSWORD: 'r00t'
            MYSQL_DATABASE: 'mirmeets2'

    phpmyadmin:
        image: phpmyadmin
        links: 
            - 'mariadb:db'
        ports:
            - 8084:80
